### ISSUE TITLE
Add a rakefile

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/ruby_repo_template#1]
And appropriate tasks:
- test
- nag
- etc

**Comment by jrhorn424** [comment]
- server

**Comment by gaand** [comment]
- [x] test
- [ ] nag
- [ ] server

`rake test` added in e2abbf97a153d01226a6a621a0671ce264178d17

**Comment by gaand** [comment]
@jrhorn424 I'm happy to add a server task, but I just realized that I'm unclear on what it should do.

**Comment by gaand** [comment]
- [x] test
- [x] nag
- [ ] server

`bin/rake nag` added in 14f53c552d11cd689b487a4ebf9101226c95dca6

**Comment by jrhorn424** [comment]
Is it appropriate to add server in rake as an alias to rails server? If so s, serve, and server should all be added.

**Comment by gaand** [comment]
@jrhorn424 This is ruby, not rails.

**Comment by raq929** [comment]
It sounds like this issue has been resolved. Should we close?

**Comment by gaand** [comment]
@raq929 Not until @jrhorn424 replies.

**Comment by jrhorn424** [comment]
@gaand @rts Would it be ok to add `ruby -r un httpd .`? I don't feel strongly about this. If @gaand disagrees I consider this closed. Thanks!

**Comment by raq929** [comment]
@gaand says 'I don't want to do that.' These are the times that I really wish tone could be expressed via text. Closing.
