### ISSUE TITLE
Fix up .gitignore

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/ruby_repo_template#11]
Remove/comment out `.rspec` and `bower.json`

@jrhorn424 I hope we can revisit the comprehensive `.gitignore`.  I'm starting to think it would be better to be more targeted.

**Comment by raq929** [comment]
@jrhorn424 was this addressed in 229948cb3a4836298092004f093592d86d9d6e2c?

**Comment by jrhorn424** [comment]
Yes it was. @gaand Does that commit align with your intent?

**Comment by gaand** [comment]
I believe it does.
