### ISSUE TITLE
Change linter rules for spec files

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/ruby_repo_template#13]
Specs often require blocks longer than the linter likes. I've been using `# rubocop:disable BlockLength` at the top of my spec files, but if there's a way to disable that rule for just spec files, that would be awesome.

**Comment by gaand** [comment]
These rules can be set in `.rubocop.yml`.

**Comment by raq929** [comment]
This was addressed in 	c4d6a8a.
